version: '3'
volumes:
   portainer_data:
services:
   redis:
     image: redis
     volumes:
       - ~/review:/data
     networks: 
       - bdp2-net
   jupyter:
     image: gorsini/bdp2_mid_term_review
     environment:
       - JUPYTER_ENABLE_LAB=yes
       - JUPYTER_TOKEN=bdp2_password
       - CHOWN_HOME=yes
       - CHOWN_HOME_OPTS=-R
     ports:
       - 80:8888
     volumes:
       - ~/review/BDP2_mid-term_review/work:/home/jovyan
     networks:
       - bdp2-net
   portainer:
     image: portainer/portainer-ce
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - portainer_data:/data 
     ports: 
       - 8000:8000
       - 443:9443
     networks:
       - bdp2-net
networks:
   bdp2-net:
